name:                no-syn
version:             0.1.0.0
github:              "lyncmi07/no-syn"
license:             GPL-3
author:              "Michael Lynch"

extra-source-files:
- README.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/no-syn#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - ordered-containers
  - containers
  - template-haskell
  - array
  - text-latin1
  - split
  - set-theory
  - transformers

executables:
  no-syn-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - no-syn
    - ordered-containers
    - containers
    - template-haskell
    - array
    - split
    - set-theory

tests:
  no-syn-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - no-syn
